### ISSUE TITLE
Compile error on Linux x86 64 on master branch

### ISSUE THREAD

**Issue by Diegovsky** [lnyaa/zig-docsearch#4]
```
./src/main.zig:52:29: error: container 'std.heap' has no member called 'direct_allocator'
    var allocator = std.heap.direct_allocator;
```

I'm using the latest zig compiler build, right from the master branch:
```
diegovsky@ryzenarch ~/zig-docsearch ((ce87ef9e…)) [1]> zig version
0.8.0-dev.1562+9f01598a4
```

**Comment by lun-4** [comment]
There are other WIP documentation efforts that would supersede this project. My focus is on other things, so, at least, don't expect for a fix to come quickly.

**Comment by Diegovsky** [comment]
It's ok! Thanks for developing this and contributing to the community, I really appreciate your efforts :)
